[package]
name = "educe"
version = "0.4.18"
authors = ["Magic Len <len@magiclen.org>"]
edition = "2018"
repository = "https://github.com/magiclen/educe"
homepage = "https://magiclen.org/educe"
keywords = ["derive", "macro", "trait", "field", "procedural"]
categories = ["no-std", "rust-patterns"]
description = "This crate provides procedural macros to help you implement Rust-built-in traits quickly."
readme = "README.md"
license = "MIT"
include = ["src/**/*", "Cargo.toml", "README.md", "LICENSE"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
syn = { version = "1", features = ["full", "extra-traits"] }
quote = "1"

enum-ordinalize = "3.1"

[dev-dependencies]
assert_approx_eq = "1.1"

[features]
default = ["Debug", "PartialEq", "Eq", "PartialOrd", "Ord", "Hash", "Default", "Clone", "Copy", "Deref", "DerefMut"]
Debug = []
PartialEq = []
Eq = []
PartialOrd = []
Ord = []
Hash = []
Default = []
Clone = []
Copy = []
Deref = []
DerefMut = []